# Generated by Django 3.1.4 on 2021-04-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20210418_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
