# Generated by Django 3.1.4 on 2021-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confpassword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
