# Generated by Django 3.1.4 on 2021-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210420_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
