# Generated by Django 3.1.4 on 2021-04-20 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20210420_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
